import { NavLink } from '@/components/nav-link/NavLink';
import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <nav className='flex items-center justify-between bg-primary'>
          <ul className='flex items-center m-0 p-2 bg-primary'>
            <li className='mr-2'>
              <NavLink href='/'>Home</NavLink>
            </li>
            <li className='mr-2'>
              <NavLink href='/movies'>Movies</NavLink>
            </li>
            <li className='mr-2'></li>
          </ul>
        </nav>
        <main className='container mx-auto'>
          {/* <nav>
            <ul className='flex flex-wrap border-b border-gray-200'>
              <li className='mr-2'>
                <Link href='/' className='tab'>
                  Popular
                </Link>
              </li>
              <li className='mr-2'>
                <Link href='/search' className='tab'>
                  Search
                </Link>
              </li>
              <li className='mr-2'>
                <Link href='/favorites' className='tab'>
                  My Favorites
                </Link>
              </li>
            </ul>
          </nav> */}
          {children}
        </main>
      </body>
    </html>
  );
}
